# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a14e8fb604375ff461b0e3c01de69d55676f8dfb621aa2c8d072ad43a333864ffc8764911517707c199e15b956390daf48217f50588c375adb83c742df332100

test:
  secret_key_base: f6c24a09240328a74eb87a21ad696378729afb92b5fc39b572e894050457efb6f15080cc1d6aef66be41f0ccffc3a64302d392a07979b3442691ea0afc6e6639

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
